#!/usr/bin/env python3
"""Batch 1: Grammar & Punctuation (50 questions) for TEAS English"""
import sqlite3, json

DB = "data/kb/teas_unified.db"

questions = [
    # --- Subject-Verb Agreement (10) ---
    {"topic": "Subject-Verb Agreement", "q": "Choose the sentence with correct subject-verb agreement.\n\nA. The collection of rare coins were displayed at the museum.\nB. The collection of rare coins was displayed at the museum.\nC. The collection of rare coins have been displayed at the museum.\nD. The collection of rare coins are being displayed at the museum.", "a": "B", "w": ["A","C","D"], "e": "'Collection' is the subject and is singular. The phrase 'of rare coins' is a prepositional phrase and does not affect subject-verb agreement.", "d": "easy"},
    {"topic": "Subject-Verb Agreement", "q": "Select the sentence with correct subject-verb agreement.\n\nA. Every one of the students have submitted the assignment.\nB. Every one of the students has submitted the assignment.\nC. Every one of the students are submitting the assignment.\nD. Every one of the students were submitting the assignment.", "a": "B", "w": ["A","C","D"], "e": "'Every one' is singular, so it requires the singular verb 'has.' Words like 'every,' 'each,' and 'either' take singular verbs.", "d": "medium"},
    {"topic": "Subject-Verb Agreement", "q": "Which sentence uses the correct verb form?\n\nA. The news about the merger are surprising.\nB. The news about the merger is surprising.\nC. The news about the merger were surprising.\nD. The news about the merger have been surprising.", "a": "B", "w": ["A","C","D"], "e": "'News' is a singular noun despite ending in -s. It always takes a singular verb.", "d": "easy"},
    {"topic": "Subject-Verb Agreement", "q": "Choose the sentence with correct subject-verb agreement.\n\nA. Mathematics are a challenging subject for many students.\nB. Mathematics is a challenging subject for many students.\nC. Mathematics have been a challenging subject for many students.\nD. Mathematics were a challenging subject for many students.", "a": "B", "w": ["A","C","D"], "e": "'Mathematics' ends in -s but is a singular noun. Other examples include physics, economics, and politics.", "d": "medium"},
    {"topic": "Subject-Verb Agreement", "q": "Select the correct verb: The committee members, along with the chairperson, ___ attending the conference.\n\nA. is\nB. are\nC. was\nD. has been", "a": "B", "w": ["A","C","D"], "e": "The subject is 'committee members' (plural). The phrase 'along with the chairperson' does not change the subject number.", "d": "medium"},
    {"topic": "Subject-Verb Agreement", "q": "Which sentence is correct?\n\nA. Bread and butter are my usual breakfast.\nB. Bread and butter is my usual breakfast.\nC. Bread and butter were my usual breakfast.\nD. Bread and butter have been my usual breakfast.", "a": "B", "w": ["A","C","D"], "e": "When 'bread and butter' refers to a single unit (a meal), it takes a singular verb. This is different from 'bread and butter are on the table.'", "d": "hard"},
    {"topic": "Subject-Verb Agreement", "q": "Choose the correct verb: Either the manager or the assistants ___ responsible for the error.\n\nA. is\nB. are\nC. was\nD. has been", "a": "B", "w": ["A","C","D"], "e": "With 'either/or,' the verb agrees with the nearer subject ('assistants,' which is plural).", "d": "medium"},
    {"topic": "Subject-Verb Agreement", "q": "Select the sentence with correct subject-verb agreement.\n\nA. A number of students was absent today.\nB. A number of students were absent today.\nC. The number of students were absent today.\nD. The number of students are absent today.", "a": "B", "w": ["A","C","D"], "e": "'A number of' takes a plural verb. 'The number of' takes a singular verb. This is a commonly tested distinction.", "d": "hard"},
    {"topic": "Subject-Verb Agreement", "q": "Which sentence uses the correct verb?\n\nA. Each of the patients require a follow-up appointment.\nB. Each of the patients requires a follow-up appointment.\nC. Each of the patients have required a follow-up appointment.\nD. Each of the patients are requiring a follow-up appointment.", "a": "B", "w": ["A","C","D"], "e": "'Each' is always singular and requires a singular verb ('requires'). Ignore the plural 'patients' in the prepositional phrase.", "d": "easy"},
    {"topic": "Subject-Verb Agreement", "q": "Choose the correct sentence.\n\nA. The data suggests a strong correlation.\nB. The data suggest a strong correlation.\nC. The data has suggested a strong correlation.\nD. The data is suggesting a strong correlation.", "a": "B", "w": ["A","C","D"], "e": "'Data' is the plural form of 'datum' and traditionally takes a plural verb ('suggest'). In scientific writing, plural usage is standard.", "d": "hard"},

    # --- Verb Tenses (10) ---
    {"topic": "Verb Tenses", "q": "Choose the sentence with the correct verb tense.\n\nA. She has went to the clinic three times this month.\nB. She has gone to the clinic three times this month.\nC. She had gone to the clinic three times this month.\nD. She have gone to the clinic three times this month.", "a": "B", "w": ["A","C","D"], "e": "'Has gone' is the correct present perfect form. 'Went' is simple past and cannot follow 'has.' 'Had gone' (past perfect) requires a reference to an earlier past event.", "d": "easy"},
    {"topic": "Verb Tenses", "q": "Select the sentence with correct verb tense usage.\n\nA. By the time the ambulance arrived, the patient died.\nB. By the time the ambulance arrived, the patient has died.\nC. By the time the ambulance arrived, the patient had died.\nD. By the time the ambulance arrived, the patient was died.", "a": "C", "w": ["A","B","D"], "e": "Past perfect ('had died') is used for an action completed before another past action ('arrived').", "d": "medium"},
    {"topic": "Verb Tenses", "q": "Which sentence uses the correct verb form?\n\nA. The researchers are conducting the experiment since January.\nB. The researchers have been conducting the experiment since January.\nC. The researchers had been conducting the experiment since January.\nD. The researchers was conducting the experiment since January.", "a": "B", "w": ["A","C","D"], "e": "'Since January' indicates an action starting in the past and continuing to the present, requiring present perfect continuous ('have been conducting').", "d": "medium"},
    {"topic": "Verb Tenses", "q": "Choose the correct verb tense.\n\nA. The train leaves at 6 AM tomorrow.\nB. The train will leave at 6 AM tomorrow.\nC. The train is leaving at 6 AM tomorrow.\nD. Both A and B are correct.", "a": "D", "w": ["C"], "e": "Simple present ('leaves') is used for scheduled future events, and 'will leave' also works for future plans. Both are grammatically correct.", "d": "hard"},
    {"topic": "Verb Tenses", "q": "Select the sentence with correct tense.\n\nA. I wish I was more prepared for the exam.\nB. I wish I were more prepared for the exam.\nC. I wish I am more prepared for the exam.\nD. I wish I be more prepared for the exam.", "a": "B", "w": ["A","C","D"], "e": "'Were' is the correct subjunctive form after 'wish' for present unreal situations, regardless of the subject.", "d": "medium"},
    {"topic": "Verb Tenses", "q": "Which sentence correctly uses the past perfect tense?\n\nA. She had completed her training before she was hired.\nB. She completed her training before she was hired.\nC. She has completed her training before she was hired.\nD. She had been completed her training before she was hired.", "a": "A", "w": ["B","C","D"], "e": "Past perfect ('had completed') correctly shows that the training was finished before another past event ('was hired').", "d": "medium"},
    {"topic": "Verb Tenses", "q": "Choose the sentence with correct progressive tense usage.\n\nA. The children were playing in the yard when it started to rain.\nB. The children played in the yard when it was starting to rain.\nC. The children have played in the yard when it started to rain.\nD. The children are playing in the yard when it started to rain.", "a": "A", "w": ["B","C","D"], "e": "Past progressive ('were playing') describes an ongoing action interrupted by another event ('started to rain').", "d": "easy"},
    {"topic": "Verb Tenses", "q": "Select the correct verb form.\n\nA. If I was you, I would accept the offer.\nB. If I were you, I would accept the offer.\nC. If I am you, I would accept the offer.\nD. If I be you, I would accept the offer.", "a": "B", "w": ["A","C","D"], "e": "The subjunctive mood uses 'were' for hypothetical conditions (contrary to fact), even with singular subjects like 'I.'", "d": "easy"},
    {"topic": "Verb Tenses", "q": "Which sentence uses the future perfect tense correctly?\n\nA. By next year, she will have graduated from nursing school.\nB. By next year, she will graduate from nursing school.\nC. By next year, she is going to graduate from nursing school.\nD. By next year, she graduates from nursing school.", "a": "A", "w": ["B","C","D"], "e": "'By next year' with 'will have graduated' is the future perfect tense, indicating completion before a future point.", "d": "medium"},
    {"topic": "Verb Tenses", "q": "Choose the sentence with the correct tense sequence.\n\nA. The patient reported that she experiences chest pain.\nB. The patient reported that she experienced chest pain.\nC. The patient reported that she is experiencing chest pain.\nD. The patient reported that she has experienced chest pain.", "a": "B", "w": ["A","C","D"], "e": "When the reporting verb is past ('reported'), the reported clause should shift to past tense ('experienced') for sequence of tenses.", "d": "medium"},

    # --- Pronoun Usage (5) ---
    {"topic": "Pronoun Usage", "q": "Choose the sentence with correct pronoun usage.\n\nA. Between you and I, the project needs more funding.\nB. Between you and me, the project needs more funding.\nC. Between you and myself, the project needs more funding.\nD. Between you and mine, the project needs more funding.", "a": "B", "w": ["A","C","D"], "e": "'Between' is a preposition and requires the object pronoun 'me,' not the subject pronoun 'I' or the reflexive 'myself.'", "d": "easy"},
    {"topic": "Pronoun Usage", "q": "Select the sentence with the correct pronoun case.\n\nA. The supervisor gave the assignment to Sarah and I.\nB. The supervisor gave the assignment to Sarah and myself.\nC. The supervisor gave the assignment to Sarah and me.\nD. The supervisor gave the assignment to Sarah's and my self.", "a": "C", "w": ["A","B","D"], "e": "The preposition 'to' requires object pronouns. 'Me' is correct; 'myself' is only used for reflexive actions.", "d": "easy"},
    {"topic": "Pronoun Usage", "q": "Which sentence uses pronouns correctly?\n\nA. Each student must bring their own calculator.\nB. Each student must bring his or her own calculator.\nC. Each student must bring its own calculator.\nD. Both A and B are acceptable.", "a": "D", "w": ["C"], "e": "Traditional grammar requires 'his or her' with 'each,' but 'their' as a singular pronoun is now widely accepted in formal writing.", "d": "hard"},
    {"topic": "Pronoun Usage", "q": "Choose the sentence with correct pronoun-antecedent agreement.\n\nA. The team won their first championship.\nB. The team won its first championship.\nC. The team won there first championship.\nD. The team won they're first championship.", "a": "B", "w": ["A","C","D"], "e": "'Team' is a collective noun treated as singular in American English, so 'its' is correct. 'Their' is common but less formal.", "d": "medium"},
    {"topic": "Pronoun Usage", "q": "Select the correct pronoun usage.\n\nA. The dog wagged it's tail happily.\nB. The dog wagged its tail happily.\nC. The dog wagged their tail happily.\nD. The dog wagged his' tail happily.", "a": "B", "w": ["A","C","D"], "e": "'Its' (no apostrophe) is the possessive pronoun. 'It's' means 'it is' or 'it has.' Animals use 'its' unless specifically named.", "d": "easy"},

    # --- Active vs Passive Voice (5) ---
    {"topic": "Active vs Passive Voice", "q": "Which sentence is written in the active voice?\n\nA. The medication was prescribed by the physician.\nB. The physician prescribed the medication.\nC. The medication has been prescribed by the physician.\nD. The medication is being prescribed by the physician.", "a": "B", "w": ["A","C","D"], "e": "Active voice has the subject performing the action: 'The physician prescribed.' Passive voice has the subject receiving the action.", "d": "easy"},
    {"topic": "Active vs Passive Voice", "q": "Choose the sentence that uses the passive voice.\n\nA. The scientist published the findings in the journal.\nB. The committee reviewed the proposal carefully.\nC. The proposal was reviewed by the committee.\nD. The teacher explained the concept to the class.", "a": "C", "w": ["A","B","D"], "e": "Passive voice uses a form of 'to be' + past participle. 'Was reviewed' is passive; the subject 'proposal' receives the action.", "d": "easy"},
    {"topic": "Active vs Passive Voice", "q": "Select the best revision to change passive voice to active voice.\n\nOriginal: The test results were analyzed by the lab technician.\n\nA. The test results were analyzed.\nB. The lab technician analyzed the test results.\nC. Analysis of the test results was done.\nD. The test results have been analyzed.", "a": "B", "w": ["A","C","D"], "e": "To convert to active voice, make the doer of the action ('the lab technician') the subject performing the verb ('analyzed').", "d": "easy"},
    {"topic": "Active vs Passive Voice", "q": "Which sentence is most appropriate in passive voice?\n\nA. The chef cooked the meal.\nB. The window was broken during the storm.\nC. The student completed the assignment.\nD. The manager approved the request.", "a": "B", "w": ["A","C","D"], "e": "Passive voice is appropriate when the actor is unknown or unimportant. Here, what broke the window is less important than the fact that it broke.", "d": "medium"},
    {"topic": "Active vs Passive Voice", "q": "Choose the active voice version of: 'The new policy was implemented by management.'\n\nA. The new policy has been implemented.\nB. Management implemented the new policy.\nC. Implementation of the new policy occurred.\nD. The new policy is being implemented.", "a": "B", "w": ["A","C","D"], "e": "Active voice places the actor ('management') as the subject and uses a direct verb ('implemented') rather than a 'to be' + participle.", "d": "easy"},

    # --- Parallel Structure (5) ---
    {"topic": "Parallel Structure", "q": "Choose the sentence with correct parallel structure.\n\nA. She likes hiking, swimming, and to ride bikes.\nB. She likes hiking, swimming, and riding bikes.\nC. She likes to hike, swimming, and riding bikes.\nD. She likes hike, swim, and riding bikes.", "a": "B", "w": ["A","C","D"], "e": "Items in a list must use the same grammatical form. 'Hiking, swimming, and riding' all use gerunds (-ing forms).", "d": "easy"},
    {"topic": "Parallel Structure", "q": "Select the sentence with proper parallelism.\n\nA. The job requires patience, dedication, and being detail-oriented.\nB. The job requires being patient, being dedicated, and attention to detail.\nC. The job requires patience, dedication, and attention to detail.\nD. The job requires to be patient, dedication, and detail-oriented.", "a": "C", "w": ["A","B","D"], "e": "All three items are noun phrases: 'patience,' 'dedication,' and 'attention to detail.' This maintains parallel structure.", "d": "medium"},
    {"topic": "Parallel Structure", "q": "Which sentence demonstrates correct parallel structure with correlative conjunctions?\n\nA. She is both intelligent and has a strong work ethic.\nB. She both is intelligent and has a strong work ethic.\nC. She is both intelligent and hardworking.\nD. Both she is intelligent and she has a strong work ethic.", "a": "C", "w": ["A","B","D"], "e": "With 'both/and,' the elements after each conjunction must be parallel: 'intelligent' (adjective) and 'hardworking' (adjective).", "d": "medium"},
    {"topic": "Parallel Structure", "q": "Choose the sentence with correct parallel structure.\n\nA. The students were told to read the chapter, to answer the questions, and that they should submit their work.\nB. The students were told to read the chapter, answer the questions, and submit their work.\nC. The students were told reading the chapter, to answer the questions, and submitting their work.\nD. The students were told to read the chapter, answering the questions, and submission of their work.", "a": "B", "w": ["A","C","D"], "e": "All three items use infinitive form: 'to read,' 'answer,' 'submit.' The shared 'to' applies to all three.", "d": "easy"},
    {"topic": "Parallel Structure", "q": "Select the sentence with correct parallelism.\n\nA. Not only did she win the award, but she also received a scholarship.\nB. Not only she won the award, but also received a scholarship.\nC. She not only won the award but receiving a scholarship.\nD. Not only did she win the award, but receiving a scholarship also.", "a": "A", "w": ["B","C","D"], "e": "'Not only did she win' (verb phrase) parallels 'but she also received' (verb phrase). Both clauses have matching structure.", "d": "hard"},

    # --- Modifiers (5) ---
    {"topic": "Modifiers", "q": "Choose the sentence that correctly avoids a dangling modifier.\n\nA. Walking through the park, the flowers smelled wonderful.\nB. Walking through the park, I noticed the flowers smelled wonderful.\nC. Walking through the park, the flowers were noticed by me.\nD. Walking through the park, it was noticed that the flowers smelled wonderful.", "a": "B", "w": ["A","C","D"], "e": "The modifying phrase 'walking through the park' must describe the subject that follows. Only 'I' can walk through a park.", "d": "easy"},
    {"topic": "Modifiers", "q": "Select the sentence with correct modifier placement.\n\nA. The patient who was coughing loudly was examined by the doctor.\nB. The patient was examined by the doctor who was coughing loudly.\nC. Coughing loudly, the doctor examined the patient.\nD. The doctor examined the patient coughing loudly.", "a": "A", "w": ["B","C","D"], "e": "The modifier 'who was coughing loudly' should be placed next to 'the patient,' not 'the doctor.'", "d": "medium"},
    {"topic": "Modifiers", "q": "Which sentence has a misplaced modifier?\n\nA. She served the cake to the children on small plates.\nB. She served the children cake on small plates.\nC. On small plates, she served the cake to the children.\nD. She almost ate the entire cake.", "a": "D", "w": ["A","B","C"], "e": "'Almost' is misplaced — it modifies 'ate' rather than 'entire.' It should be 'She ate almost the entire cake' to mean she ate most of it.", "d": "hard"},
    {"topic": "Modifiers", "q": "Choose the sentence that corrects the dangling modifier.\n\nOriginal: After finishing the report, the computer was shut down.\n\nA. After finishing the report, the computer was shut down by me.\nB. After I finished the report, I shut down the computer.\nC. After the report was finished, the computer was shut down.\nD. After finishing the report, shutting down the computer occurred.", "a": "B", "w": ["A","C","D"], "e": "The original implies the computer finished the report. The fix provides a logical subject ('I') for both 'finishing' and 'shutting down.'", "d": "easy"},
    {"topic": "Modifiers", "q": "Select the sentence with correct modifier usage.\n\nA. The chef only added salt to the soup.\nB. The chef added only salt to the soup.\nC. Only the chef added salt to the soup.\nD. The chef added salt only to the soup.", "a": "D", "w": ["A","B","C"], "e": "Placement of 'only' changes meaning. 'Only to the soup' means salt was added to nothing else. Context determines which placement is intended.", "d": "hard"},

    # --- Sentence Structure (5) ---
    {"topic": "Sentence Structure", "q": "Choose the sentence that is a simple sentence.\n\nA. Although it was raining, we went for a walk.\nB. The cat sat on the windowsill and watched the birds.\nC. She loves reading, and he enjoys hiking.\nD. Because she studied hard, she passed the exam.", "a": "B", "w": ["A","C","D"], "e": "A simple sentence has one independent clause. 'The cat sat on the windowsill and watched the birds' has one subject with a compound verb.", "d": "medium"},
    {"topic": "Sentence Structure", "q": "Select the compound sentence.\n\nA. The students completed the assignment on time.\nB. Since the deadline was extended, the students had more time.\nC. The students completed the assignment, but they forgot to submit it.\nD. The students who completed the assignment received full credit.", "a": "C", "w": ["A","B","D"], "e": "A compound sentence has two independent clauses joined by a coordinating conjunction (FANBOYS). 'But' joins two independent clauses here.", "d": "easy"},
    {"topic": "Sentence Structure", "q": "Which sentence is a complex sentence?\n\nA. She enjoys cooking and baking.\nB. The recipe calls for flour, sugar, and eggs.\nC. When the timer rang, she removed the cake from the oven.\nD. He opened the door and walked inside.", "a": "C", "w": ["A","B","D"], "e": "A complex sentence has one independent clause and one or more dependent clauses. 'When the timer rang' is a dependent clause.", "d": "easy"},
    {"topic": "Sentence Structure", "q": "Choose the compound-complex sentence.\n\nA. She went to the store, and she bought milk.\nB. Although she was tired, she finished her homework, and she submitted it on time.\nC. After the meeting ended, they went home.\nD. The dog barked at the mailman.", "a": "B", "w": ["A","C","D"], "e": "A compound-complex sentence has at least two independent clauses and one dependent clause. This sentence has two independent clauses joined by 'and' and one dependent clause starting with 'although.'", "d": "hard"},
    {"topic": "Sentence Structure", "q": "Select the sentence fragment.\n\nA. Running through the field.\nB. She ran through the field.\nC. After she ran through the field, she was tired.\nD. She ran through the field and was tired.", "a": "A", "w": ["B","C","D"], "e": "A fragment lacks a complete subject-verb pair or expresses an incomplete thought. 'Running through the field' is a participial phrase, not a complete sentence.", "d": "easy"},

    # --- Comma Usage (5) ---
    {"topic": "Comma Usage", "q": "Choose the sentence with correct comma usage.\n\nA. The tall, dark, and handsome man entered the room.\nB. The tall dark and handsome man entered the room.\nC. The tall, dark and handsome, man entered the room.\nD. The tall, dark, and handsome, man entered the room.", "a": "A", "w": ["B","C","D"], "e": "In a list of three or more items, use commas between each item (the Oxford comma is standard in academic writing).", "d": "easy"},
    {"topic": "Comma Usage", "q": "Select the sentence with correct comma placement.\n\nA. However the results were inconclusive.\nB. However, the results were inconclusive.\nC. The results however, were inconclusive.\nD. The results were, however inconclusive.", "a": "B", "w": ["A","C","D"], "e": "A conjunctive adverb ('however') at the beginning of a sentence is followed by a comma.", "d": "easy"},
    {"topic": "Comma Usage", "q": "Which sentence correctly uses a comma with an introductory clause?\n\nA. After the lecture ended the students left.\nB. After the lecture ended, the students left.\nC. After, the lecture ended the students left.\nD. After the lecture, ended the students left.", "a": "B", "w": ["A","C","D"], "e": "An introductory dependent clause should be followed by a comma before the main clause.", "d": "easy"},
    {"topic": "Comma Usage", "q": "Choose the sentence with correct comma usage for a non-restrictive clause.\n\nA. My sister who lives in New York is a doctor.\nB. My sister, who lives in New York, is a doctor.\nC. My sister who, lives in New York is a doctor.\nD. My sister, who lives in New York is a doctor.", "a": "B", "w": ["A","C","D"], "e": "A non-restrictive clause adds extra information and is set off by commas on both sides. Since the speaker has one sister, the clause is non-restrictive.", "d": "medium"},
    {"topic": "Comma Usage", "q": "Select the sentence with correct comma usage.\n\nA. He bought apples, oranges, bananas and grapes.\nB. He bought apples, oranges, bananas, and grapes.\nC. He bought, apples, oranges, bananas, and grapes.\nD. He bought apples oranges bananas and grapes.", "a": "B", "w": ["A","C","D"], "e": "Use commas to separate items in a series, including before the final 'and' (Oxford comma). No comma follows the verb.", "d": "easy"},

    # --- Semicolon and Colon Usage (5) ---
    {"topic": "Semicolon and Colon Usage", "q": "Choose the sentence with correct semicolon usage.\n\nA. She loves coffee; and tea.\nB. The weather was cold; therefore, we stayed indoors.\nC. She loves; coffee and tea.\nD. The weather was cold; we stayed indoors; because it was raining.", "a": "B", "w": ["A","C","D"], "e": "A semicolon connects two closely related independent clauses. Option B correctly uses a semicolon before 'therefore' (conjunctive adverb) and a comma after it.", "d": "medium"},
    {"topic": "Semicolon and Colon Usage", "q": "Select the sentence with correct colon usage.\n\nA. The recipe requires the following ingredients: flour, sugar, and eggs.\nB. The recipe requires: flour, sugar, and eggs.\nC. The ingredients for the recipe are: flour, sugar, and eggs.\nD. The recipe requires the following ingredients, flour, sugar, and eggs.", "a": "A", "w": ["B","C","D"], "e": "A colon follows an independent clause that introduces a list. 'The recipe requires the following ingredients' is a complete clause.", "d": "easy"},
    {"topic": "Semicolon and Colon Usage", "q": "Which sentence correctly uses a semicolon?\n\nA. I have lived in Miami; and Atlanta.\nB. Some people prefer cats; others prefer dogs.\nC. The meeting is at 3; PM.\nD. Although it rained; we went hiking.", "a": "B", "w": ["A","C","D"], "e": "A semicolon joins two independent clauses without a coordinating conjunction. 'Some people prefer cats' and 'others prefer dogs' are both complete thoughts.", "d": "easy"},
    {"topic": "Semicolon and Colon Usage", "q": "Choose the correctly punctuated sentence.\n\nA. The directions are as follows: turn left, go two miles, then turn right.\nB. The directions are as follows, turn left, go two miles, then turn right.\nC. The directions are as follows turn left, go two miles, then turn right.\nD. The directions are: as follows turn left, go two miles, then turn right.", "a": "A", "w": ["B","C","D"], "e": "A colon introduces a series of directions or instructions after a complete independent clause ('The directions are as follows').", "d": "easy"},
    {"topic": "Semicolon and Colon Usage", "q": "Select the sentence that correctly uses a semicolon with items containing commas.\n\nA. On our trip, we visited Paris, France; Rome, Italy; and Madrid, Spain.\nB. On our trip, we visited Paris France, Rome Italy, and Madrid Spain.\nC. On our trip we visited; Paris, France; Rome, Italy; and Madrid, Spain.\nD. On our trip, we visited Paris; France, Rome; Italy, and Madrid; Spain.", "a": "A", "w": ["B","C","D"], "e": "Semicolons separate items in a series when one or more items contain internal commas. This is sometimes called the 'super comma.'", "d": "hard"},
]

def insert_batch(qs):
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    count = 0
    for q in qs:
        c.execute("""INSERT INTO questions (subject, topic, question_text, correct_answer, wrong_answers, explanation, difficulty)
                     VALUES (?, ?, ?, ?, ?, ?, ?)""",
                  ("english", q["topic"], q["q"], q["a"], json.dumps(q["w"]), q["e"], q["d"]))
        count += 1
    conn.commit()
    conn.close()
    return count

if __name__ == "__main__":
    n = insert_batch(questions)
    print(f"Inserted {n} questions")
